
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import { SimulationConfig } from '../types';

const defaults: Omit<SimulationConfig, 'id' | 'name' | 'description' | 'instrument' | 'shapeType' | 'themeColor'> = {
    vertexCount: 4,
    gravity: 0.2,
    friction: 0.001,
    restitution: 0.9,
    rotationSpeed: 0.005,
    ballCount: 3,
    ballSize: 6,
    initialSpeed: 5,
    flock: {
        enabled: false,
        boidCount: 0,
        perceptionRadius: 50,
        maxForce: 0.05,
        maxSpeed: 2,
        separationWeight: 1.5,
        alignmentWeight: 1.0,
        cohesionWeight: 1.0,
        color: '#ffffff',
        personality: 'free',
        euclideanHits: 4,  // Default: 4-on-the-floor ish (4 hits in 16 steps)
        euclideanSteps: 16
    }
};

export const presets: SimulationConfig[] = [
  {
    ...defaults,
    id: 1,
    name: "Gummy Bass",
    shapeType: 'triangle',
    vertexCount: 3,
    gravity: 0.6, // Heavier feel
    restitution: 0.92, // Bouncy but stable
    friction: 0.005,
    ballCount: 1,
    ballSize: 25,
    description: "Elastic sub-bass with impact compression.",
    themeColor: "#e11d48", 
    instrument: {
        soundId: 'ana_bass',
        sourceType: 'synth',
        waveform: 'sawtooth',
        baseOctave: 2,
        attack: 0.05,
        decay: 0.2,
        sustain: 0.6,
        release: 0.3,
        detuneAmount: 12,
        subLevel: 0.8,
        filterType: 'lowpass',
        filterFreq: 250, 
        filterQ: 2,
        wobbleAmount: 0.3,
        wobbleSpeed: 4,
        timbre: 0.7,
        time: 0.2,
        vol: 0.65, 
        pan: 0,
        chaos: 0.2, 
    },
    flock: { ...defaults.flock, euclideanHits: 3, euclideanSteps: 8 } 
  },
  {
    ...defaults,
    id: 2,
    name: "Neon Neuro",
    shapeType: 'hexagon',
    vertexCount: 6,
    gravity: 0.1,
    friction: 0.001,
    restitution: 0.98,
    ballCount: 4,
    ballSize: 8,
    rotationSpeed: 0.015,
    description: "Fast-moving neural sparks with spatial panning.",
    themeColor: "#06b6d4", 
    instrument: {
        soundId: 'dig_bell',
        sourceType: 'synth',
        waveform: 'sine',
        baseOctave: 5,
        attack: 0.01,
        decay: 0.3,
        sustain: 0.1,
        release: 1.2,
        detuneAmount: 5,
        filterType: 'highpass',
        filterFreq: 800,
        bitCrush: 0.4,
        timbre: 0.3,
        vol: 0.25,
        pan: 0,
        spatialMod: true,
        chaos: 0.1
    },
    flock: { ...defaults.flock, euclideanHits: 5, euclideanSteps: 16 }
  },
  {
    ...defaults,
    id: 3,
    name: "Wobble Pluck",
    shapeType: 'square',
    vertexCount: 4,
    gravity: 0.3,
    restitution: 0.9,
    rotationSpeed: 0.005,
    ballCount: 3,
    ballSize: 10,
    description: "Bouncy square waves with resonant zaps.",
    themeColor: "#f59e0b",
    instrument: {
        soundId: 'ana_lead',
        sourceType: 'synth',
        waveform: 'square',
        baseOctave: 4,
        attack: 0.01,
        decay: 0.1,
        sustain: 0.5,
        release: 0.2,
        detuneAmount: 8,
        wobbleAmount: 0.6,
        wobbleSpeed: 12, 
        filterType: 'bandpass',
        filterFreq: 1200,
        timbre: 0.8,
        vol: 0.2,
        pan: 0,
        spatialMod: true,
    }
  },
  {
    ...defaults,
    id: 4,
    name: "Crystal Rain",
    shapeType: 'octagon',
    vertexCount: 8,
    gravity: 0.6,
    ballCount: 5,
    ballSize: 4,
    restitution: 0.8,
    rotationSpeed: 0.002,
    description: "Tiny droplets. High pitched and clear.",
    themeColor: "#a855f7",
    instrument: {
        soundId: 'dig_chime',
        sourceType: 'synth',
        waveform: 'square',
        baseOctave: 5,
        attack: 0.01,
        decay: 0.2,
        sustain: 0,
        release: 0.5,
        detuneAmount: 0,
        filterType: 'bandpass',
        filterFreq: 1500,
        filterQ: 5, 
        spatialMod: true,
        timbre: 0.5,
        vol: 0.25,
        pan: 0,
    }
  },
  {
    ...defaults,
    id: 5,
    name: "Drone Cell",
    shapeType: 'star',
    vertexCount: 5,
    gravity: 0.00,
    ballCount: 6,
    ballSize: 6,
    initialSpeed: 3,
    rotationSpeed: 0.001,
    friction: 0.001, 
    restitution: 0.9, 
    description: "Slow moving, biological textures.",
    themeColor: "#8b5cf6",
    instrument: {
        soundId: 'atm_nebula',
        sourceType: 'synth',
        waveform: 'sawtooth',
        baseOctave: 2,
        attack: 0.1, // Faster attack
        decay: 2.0,
        sustain: 1.0,
        release: 3.0,
        detuneAmount: 20,
        filterType: 'lowpass',
        filterFreq: 300,
        spatialMod: true, 
        vol: 0.3, 
        time: 0.9,
        pan: 0,
        chaos: 0.15
    }
  },
    {
    ...defaults,
    id: 6,
    name: "Glitch Swarm",
    shapeType: 'pentagon',
    vertexCount: 5,
    gravity: 0.0,
    friction: 0.005, 
    restitution: 0.98, // STABLE: 0.98 ensures energy decays naturally
    rotationSpeed: 0.05, 
    ballCount: 8,
    ballSize: 3,
    initialSpeed: 12, 
    description: "Chaotic, high-speed collision particles.",
    themeColor: "#6366f1",
    instrument: {
        soundId: 'dig_glitch',
        sourceType: 'synth',
        waveform: 'sawtooth',
        baseOctave: 6,
        attack: 0.001,
        decay: 0.02,
        sustain: 0,
        release: 0.02,
        vol: 0.2, 
        pan: 0,
        spatialMod: true,
        detuneAmount: 50, 
        filterType: 'highpass',
        filterFreq: 2000,
        wobbleAmount: 0,
        bitCrush: 0.8,
        chaos: 0.6
    }
  }
];
